### ISSUE TITLE
A riot example code for configuring a gpio pin as external interrupt for samr21 

### ISSUE THREAD

**Issue by shreeharsha22** [JanmanX/MicroOS#11]
Hai,
can any one provide the code for configuring a gpio pin as external interrupt for samr21. 

Thanks in advance.
Regards,
Shreeharsha I

**Comment by JanmanX** [comment]
If I am not mistaken, SAMR21 is some kind of ARM-based microcontroller.

MicroOS is a school project for an minimal x86 operating system. This is a wrong place to ask that question.

/Jan
